import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { saveAs } from 'file-saver'; // Helper to save the file
import './App.css';
import starIcon from './images/starIcon.png';

// --- 1. Define Professional PDF Styles ---
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.5,
  },
  header: {
    fontSize: 20,
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 'bold',
    textDecoration: 'underline',
  },
  questionBox: {
    marginBottom: 15,
    paddingBottom: 10,
    borderBottom: '1px solid #eee',
  },
  questionText: {
    fontSize: 12,
    fontWeight: 'bold', // Make questions pop
    marginBottom: 5,
    color: '#000',
  },
  answerSection: {
    marginLeft: 10,
    marginBottom: 5,
    color: '#333',
  },
  keyConceptBox: {
    marginTop: 5,
    padding: 8,
    backgroundColor: '#f0f8ff', // Light blue background for concepts
    borderRadius: 4,
    fontSize: 10,
    color: '#0056b3',
  },
  boldLabel: {
    fontWeight: 'bold',
    color: '#222',
  }
});

// --- 2. The PDF Document Component ---
const ExamDocument = ({ content }) => {
  // We parse the raw text into sections based on "QUESTION"
  const sections = content.split(/QUESTION \d+[:.]?/).filter(s => s.trim().length > 0);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>Exam Solutions & Explanations</Text>
        
        {sections.map((section, index) => {
          // A bit of string magic to separate Question from Answer if possible
          // This relies on Gemini following our prompt instructions
          const parts = section.split("ANSWER:");
          const questionText = parts[0] ? parts[0].trim() : "";
          const answerText = parts[1] ? parts[1].trim() : "";

          return (
            <View key={index} style={styles.questionBox}>
              <Text style={styles.questionText}>Question {index + 1}: {questionText}</Text>
              
              {answerText && (
                <View style={styles.answerSection}>
                  <Text style={styles.boldLabel}>Answer:</Text>
                  <Text>{answerText}</Text>
                </View>
              )}
            </View>
          );
        })}
        
        <Text style={{ textAlign: 'center', marginTop: 20, fontSize: 10, color: 'gray' }}>
          Generated by Gemini 2.0 • AI Exam Solver
        </Text>
      </Page>
    </Document>
  );
};

function App() {
  const [file, setFile] = useState(null);
  const [apiKey, setApiKey] = useState("");
  const [loading, setLoading] = useState(false);
  const [generatedText, setGeneratedText] = useState("");
  const [errorLog, setErrorLog] = useState("");
  const [words, setWords] = useState(250); // Max words per answer

  const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result.split(',')[1]);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const handleGenerate = async () => {
    if (!file || !apiKey) return alert("Please provide API Key and File");
    
    setLoading(true);
    setErrorLog("");

    try {
      const ai = new GoogleGenAI({ apiKey });
      const base64Data = await fileToBase64(file);

      // --- PROMPT FOR STRUCTURED DATA ---
      const prompt = `
        You are an expert exam solver. 
        Read the attached PDF. Solve every question.
        
        CRITICAL FORMATTING RULES:
        1. Start every new question exactly with the text: "QUESTION X:" (where X is the number).
        2. Immediately follow the question with the text "ANSWER:".
        3. Put the detailed explanation, examples, and key concepts AFTER "ANSWER:".
        4. Do NOT use Markdown (no **bold** or # headings).
        5. Keep it text-only but structured.
        6. Answer should not exceed ${words} words per question.
        7. Mention question also after "QUESTION X:" for clarity.
      `;

      // Using Gemini 2.0 Pro (Experimental)
      // Note: If this hits a limit, switch back to 'gemini-2.0-flash'
      const result = await ai.models.generateContent({
        model: 'gemini-2.0-flash', 
        contents: [{
          role: 'user',
          parts: [{ text: prompt }, { inlineData: { mimeType: "application/pdf", data: base64Data } }]
        }]
      });

      setGeneratedText(result.text);

    } catch (err) {
      console.error(err);
      setErrorLog(err.message.includes("429") 
        ? "⚠️ Gemini 2.0 Pro is busy/limited. Try switching to 'gemini-2.0-flash' in the code." 
        : "Error: " + err.message);
    } finally {
      setLoading(false);
    }
  };

  // --- 3. Generate and Download the React-PDF Blob ---
  const handleDownloadPDF = async () => {
    if (!generatedText) return;
    try {
      const blob = await pdf(<ExamDocument content={generatedText} />).toBlob();
      saveAs(blob, "Exam_Solutions.pdf");
    } catch (e) {
      alert("Error generating PDF: " + e.message);
    }
  };

  return (
    <div className="App">
      <header className="header">
        <h1>✨ AI Exam Solver </h1>
        <p>Powered by Gemini 2.0  & React-PDF</p>
      </header>

      <div className="container">
        {errorLog && <div className="error-box">{errorLog}</div>}

        <div className="input-group">
          <label>API Key:</label>
          <input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} />
        </div>

        <div className="input-group">
          <label>Upload PDF:</label>
          <input type="file" onChange={(e) => setFile(e.target.files[0])} />
        </div>

        <div className="input-group">
          <label>Max Words per Answer:</label>
          <input type="number" value={words} onChange={(e) => setWords(e.target.value)} />
        </div>

        <button className="generate-btn" onClick={handleGenerate} disabled={loading}>
          {loading ? "Thinking (Gemini 2.0)..." : "Solve Questions"}
        </button>

        {generatedText && (
          <div className="result-area">
            <h3>✅ Solutions Ready!</h3>
            <p>The AI has solved the questions. Click below to download the professional PDF.</p>
            <button className="download-btn" onClick={handleDownloadPDF}>
              Download Formatted PDF
            </button>
            
            {/* Debug View */}
            <details style={{marginTop: '20px', color: '#666'}}>
              <summary>View Raw Text</summary>
              <pre className="preview-box">{generatedText}</pre>
            </details>
          </div>
        )}
      </div>
      <footer className="footer">
        <p>Mark star to support this project! <a href="https://github.com/gyanshankar1708/PDF-Solver" target="_blank" rel="noopener noreferrer"><img src={starIcon} alt="Star Icon" width={20} /></a></p>
      </footer>
    </div>
  );
}

export default App;